
services:
  postgres:
    image: postgres:latest
    container_name: sm-postgres
    environment:
      POSTGRES_DB: smart_menu
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sm-network

  redis:
    image: redis:latest
    container_name: sm-redis
    ports:
      - "6379:6379"
    environment:
      REDIS_HOST: redis
    networks:
      - sm-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]

  menu-app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: sm-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/smart_menu
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"
    volumes:
      - uploads_data:/app/uploads/files
    networks:
      - sm-network
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

networks:
  sm-network:
    driver: bridge

volumes:
  postgres_data:
  uploads_data:





