global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: '/api/actuator/prometheus'
    static_configs:
      - targets: ['172.17.0.1:8080']  # or 'localhost:8080' if not using Docker
